#!/bin/sh

NAME=musicbozz
LOGDIR=/var/tmp/$NAME

if [ ! -d $LOGDIR ] ; then
  mkdir -p $LOGDIR
fi
chown -R nobody $LOGDIR
rm -f ./main-*
ln -s $LOGDIR ./main-$NAME

exec setuidgid nobody multilog t s50000000 n20 ./main-$NAME
